# Generated by Django 2.0.1 on 2018-02-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='experience',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='CoverImageURL',
            new_name='coverImageURL',
        ),
        migrations.RemoveField(
            model_name='category',
            name='text',
        ),
        migrations.AddField(
            model_name='experience',
            name='fbVideo',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='experience',
            name='imageText',
            field=models.TextField(default='NONE'),
        ),
        migrations.AddField(
            model_name='experience',
            name='youTubeID',
            field=models.CharField(default='NONE', max_length=15),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
