# Generated by Django 2.0.1 on 2018-02-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180217_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='link',
            field=models.CharField(default='NONE', max_length=50),
        ),
    ]
