# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_experience_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name=b'fbVideo',
        ),
        migrations.RemoveField(
            model_name='experience',
            name=b'imageText',
        ),
        migrations.RemoveField(
            model_name='experience',
            name=b'slug',
        ),
        migrations.RemoveField(
            model_name='experience',
            name=b'text',
        ),
        migrations.RemoveField(
            model_name='experience',
            name=b'youTubeID',
        ),
        migrations.AddField(
            model_name='category',
            name='nameEN',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='experience',
            name='descriptionEN',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='experience',
            name='nameEN',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='link',
            field=models.CharField(max_length=50),
        ),
    ]
