# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180619_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='nameEN',
            field=models.CharField(default='', max_length=50),
        ),
    ]
